---
name: Ansible CI
on:
  workflow_call:
    inputs:
      collection:
        type: string
        required: true
jobs:
  lint-roles:
    name: "Run ansible-lint"
    uses: ./.github/workflows/ansible-lint.yml
    with:
      collection: ${{ inputs.collection }}
      target: roles
  lint-playbooks:
    name: "Run ansible-lint"
    uses: ./.github/workflows/ansible-lint.yml
    with:
      collection: ${{ inputs.collection }}
      target: playbooks
  test-units:
    name: "Run unit tests"
    uses: ./.github/workflows/ansible-test.yml
    with:
      testing-type: units
      collection: ${{ inputs.collection }}
  test-sanity:
    name: "Run sanity tests"
    uses: ./.github/workflows/ansible-test.yml
    with:
      testing-type: sanity
      collection: ${{ inputs.collection }}
  test-integration:
    name: "Run integration tests"
    uses: ./.github/workflows/ansible-test.yml
    with:
      testing-type: integration
      collection: ${{ inputs.collection }}
  black:
    name: "Format using black"
    uses: ./.github/workflows/black.yml
    with:
      collection: ${{ inputs.collection }}
