---
name: Ansible CI
on:
  workflow_call:
    inputs:
      collection:
        type: string
        required: true
jobs:
  lint:
    uses: famedly/github-workflows/.github/workflows/ansible-lint.yml
    with:
      collection: ${{ inputs.collection }}
  test-units:
    uses: famedly/github-workflows/.github/workflows/ansible-test.yml
    with:
      collection: ${{ inputs.collection }}
      testing-type: units
  test-sanity:
    uses: famedly/github-workflows/.github/workflows/ansible-test.yml
    with:
      collection: ${{ inputs.collection }}
      testing-type: sanity
  test-integration:
    uses: famedly/github-workflows/.github/workflows/ansible-test.yml
    with:
      collection: ${{ inputs.collection }}
      testing-type: integration
