---
name: Ansible Lint
on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
      collection:
        type: string
        required: true

jobs:
  lint:
    strategy:
      matrix:
        python_version:
          - "3.11"
        ansible_version:
          - "8.3.0"

    name: "Run Ansible lint"
    runs-on: ubuntu-latest
    container: docker-oss.nexus.famedly.de/ansible:py-${{ matrix.python_version }}-ansible-${{ matrix.ansible_version }}
    defaults:
      run:
        shell: bash
        working-directory: "ansible_collections/${{ inputs.collection }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: "ansible_collections/${{ inputs.collection }}"

      - name: Prepare env
        run: |
          export SUBMODULES=$(for path in $(git submodule --quiet foreach pwd); do echo "${path#$(pwd)/}/"; done)
          echo "EXCLUDE=${SUBMODULES:+--exclude ${SUBMODULES}}" >> $GITHUB_ENV

      - name: Install galaxy dependencies
        run: |
          find . -iname 'requirements.yml' -exec ansible-galaxy install -r {} \;

      - name: Run Ansible Lint
        run: |
          ansible-lint \
          --offline \
          --profile safety \
          --skip-list "name[play],name[template],fqcn[action-core],no-tabs" \
          --enable-list "no-handler,no-relative-paths,ignore-errors,meta-incorrect,meta-no-info,meta-no-tags,fqcn" \
          ${{ env.EXCLUDE }} ${{ inputs.target }}
