---
name: Black formatting
on:
  workflow_call:
    inputs:
      collection:
        type: string
        required: true
jobs:
  black:
    strategy:
      matrix:
        python_version:
          - "3.11"
        ansible_version:
          - "8.3.0"
    name: "Run Black"
    runs-on: ubuntu-latest
    container: registry.famedly.net/docker-oss/ansible:py-${{ matrix.python_version }}-ansible-${{ matrix.ansible_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
        with:
          submodules: recursive
          path: "ansible_collections/${{ inputs.collection }}"

      - name: Run Black
        uses: famedly/black@6af7d1109693c4ad3af08ecbc34649c232b47a6d
        with:
          options: "--check --verbose"
