---
name: Black formatting
on:
  workflow_call:
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: famedly/black@stable
        with:
          options: "--check --verbose"
          src: "plugins tests"
