---
name: Docker Workflow

on:
  workflow_call:
    inputs:
      registry:
        description: "Registry to upload images to"
        default: ghcr.io
        required: false
        type: string
      registry_user:
        description: "Username for the container registry"
        default: ${{ github.actor }}
        required: false
        type: string
      image_name:
        description: "Name of the image to be pushed"
        default: ${{ github.repository }}
        required: false
        type: string
      push:
        description: "Whether to push the image, or just build"
        required: true
        type: boolean

jobs:
  docker:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ inputs.registry }}
        if: inputs.push
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry_user }}
          password: ${{ secrets.registry_password || secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
